## Đề Thi Thực Hành Đại Số Tuyến Tính

In [6]:
#Cau1

import numpy as np
from math import acos, degrees

# Khởi tạo vector và ma trận
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1,  4, -2],
    [0,  2, 5]
])

# a) Tính A + B và 2A + 3B
sum_AB = A + B
linear_combination = 2 * A + 3 * B

# b) Tính tích vô hướng và góc giữa 2 vector
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = round(degrees(acos(cos_theta)), 3)

# c) Tính tích ma trận C * C^T
CCT = np.dot(C, C.T)

print("a) A + B =", sum_AB)
print("   2A + 3B =", linear_combination)

print("\nb) A · B =", dot_product)
print("   Góc giữa A và B (độ):", angle_deg)

print("\nc) Ma trận C * C^T:")
print(CCT)


a) A + B = [2 3 1 6]
   2A + 3B = [ 3 11  2 14]

b) A · B = -5
   Góc giữa A và B (độ): 99.594

c) Ma trận C * C^T:
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [5]:
import numpy as np

# a) Khai báo ma trận M và N
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính tích M × N
product = np.dot(M, N)

# b) Tính định thức của M (nếu có thể)
try:
    det_M = np.linalg.det(M)
    det_possible = True
except np.linalg.LinAlgError:
    det_possible = False
    det_M = None

# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)

# In kết quả
print("a) Ma trận tích M x N:")
print(product)

print("\nb) Định thức của M:")
if det_possible:
    print("det(M) =", round(det_M, 3))
else:
    print("Không thể tính định thức vì M không phải ma trận vuông.")

print("\nc) Hạng của ma trận N:")
print("rank(N) =", rank_N)


a) Ma trận tích M x N:
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M:
det(M) = 409.0

c) Hạng của ma trận N:
rank(N) = 4


In [4]:
#Cau3

import numpy as np

# Khai báo ma trận P và vector b
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

b = np.array([6, 8, 3, 7])  # Sửa lại vector b theo hệ phương trình: [6, 8, 3, 7]

# a) Tìm nghịch đảo của ma trận P
try:
    P_inv = np.linalg.inv(P)
    invertible = True
except np.linalg.LinAlgError:
    invertible = False
    P_inv = None

# b) Giải hệ phương trình P·x = b
if invertible:
    x = np.dot(P_inv, b)
else:
    x = None

# c) Kiểm tra nghiệm: P · x có bằng b không?
if x is not None:
    check_b = np.dot(P, x)
else:
    check_b = None

# In kết quả
print("a) Nghịch đảo của ma trận P:")
if invertible:
    print(np.round(P_inv, 3))
else:
    print("Ma trận P không khả nghịch (không có nghịch đảo).")

print("\nb) Nghiệm của hệ phương trình P·x = b:")
if x is not None:
    print("Nghiệm x =", np.round(x, 3))
else:
    print("Không thể giải vì ma trận P không khả nghịch.")

print("\nc) Kiểm tra nghiệm P·x so sánh với vector b:")
if check_b is not None:
    print("P·x =", np.round(check_b, 3))
    print("So sánh với vector b:", b)
else:
    print("Không thể kiểm tra nghiệm.")

a) Nghịch đảo của ma trận P:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b) Nghiệm của hệ phương trình P·x = b:
Nghiệm x = [2.    1.714 0.429 0.857]

c) Kiểm tra nghiệm P·x so sánh với vector b:
P·x = [6. 8. 3. 7.]
So sánh với vector b: [6 8 3 7]


In [3]:
#Cau4

import numpy as np

# a) Khai báo ma trận Q
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# a) Tìm giá trị riêng và vector riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)

# b) Vector riêng tương ứng

# c) Chuẩn hóa vector riêng
normalized_vectors = []
for v in eigenvectors.T:
    norm = np.linalg.norm(v)
    normalized_vectors.append(v / norm)
normalized_vectors = np.array(normalized_vectors)

print("a) Giá trị riêng:")
print(np.round(eigenvalues, 3))

print("\nb) Vector riêng (eigenvectors):")
print(np.round(eigenvectors, 3))

print("\nc) Vector riêng sau khi chuẩn hóa:")
print(np.round(normalized_vectors, 3))


a) Giá trị riêng:
[6.355+0.j    2.822+1.077j 2.822-1.077j]

b) Vector riêng (eigenvectors):
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c) Vector riêng sau khi chuẩn hóa:
[[ 0.748+0.j    -0.189+0.j     0.636+0.j   ]
 [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
 [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]]


In [2]:
#Cau5

import numpy as np

R = np.array([
    [4, 1, 2],
    [1, 3, -2],
    [0, 2, 5]
])

b = np.array([12, 5, 9])

# a) Giải hệ Rx = b bằng np.linalg.solve()
x_direct = np.linalg.solve(R, b)

# b) Kiểm tra khả nghịch và giải lại bằng nghịch đảo
det_R = np.linalg.det(R)
invertible = not np.isclose(det_R, 0)

if invertible:
    R_inv = np.linalg.inv(R)
    x_inverse = np.dot(R_inv, b)
else:
    R_inv = None
    x_inverse = None

# c) Tính chuẩn Frobenius của ma trận R
frobenius_norm = np.linalg.norm(R, 'fro')

print("a) Nghiệm hệ phương trình Rx = b:")
print("x =", np.round(x_direct, 3))

print("\nb) Ma trận R khả nghịch?", invertible)
if invertible:
    print("Ma trận nghịch đảo R⁻¹:")
    print(np.round(R_inv, 3))
    print("Nghiệm bằng cách dùng R⁻¹ * b:")
    print("x =", np.round(x_inverse, 3))

print("\nc) Chuẩn Frobenius của R:", round(frobenius_norm, 3))


a) Nghiệm hệ phương trình Rx = b:
x = [2.013 1.733 1.107]

b) Ma trận R khả nghịch? True
Ma trận nghịch đảo R⁻¹:
[[ 0.253 -0.013 -0.107]
 [-0.067  0.267  0.133]
 [ 0.027 -0.107  0.147]]
Nghiệm bằng cách dùng R⁻¹ * b:
x = [2.013 1.733 1.107]

c) Chuẩn Frobenius của R: 8.0
