### 1.2.1. Các phép xử lý với danh sách

In [ ]:
danhsach1 = [1., 3.]
danhsach2 = [5., 7.]
danhsach = danhsach1 + danhsach2

print(danhsach)

[1.0, 3.0, 5.0, 7.0]


In [ ]:
danhsach_gapdoi = 2 * danhsach 

print(danhsach_gapdoi)

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]


In [ ]:
danhsach * 2

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [ ]:
danhsach / 2 

TypeError: unsupported operand type(s) for /: 'list' and 'int'

- Ghép các danh sách bằng lệnh zip:
- Giả sử có 1 bạn học 4 môn với thứ tự các môn và điểm số như 3 danh sách bên dưới, chúng ta cần ghép cặp từng môn học 

In [ ]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)

tap_hop = set(anh_xa) # chuyển thành dạng tập hợp
tap_hop 

lay_TT, lay_monhoc , lay_diem = zip(*anh_xa)
lay_monhoc

print(tap_hop)
print(lay_TT)
print(lay_monhoc)

ValueError: not enough values to unpack (expected 3, got 0)

### Xây dựng danh sách: Bên cạnh những cách khai báo danh sách thông thường như: khai báo
### sẵn hoặc khai báo list rỗng rồi bổ sung phần tử bằng lệnh append, cơ chế sinh tập hợp list
### trong Python còn có thể thực hiện bằng các cách sau: 

In [ ]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5,10), range(15,20)))
tap_sinh


[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [ ]:
list(zip(range(4), range(7, 12), reversed(range(11))))

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

### 1.2.2. Lệnh thực thi một tập tin python 

In [ ]:
mylist = [100, 200, 300]
a = b = c = mylist
print(a, b, c)

a = b = c = 0
mylist = []


[100, 200, 300] [100, 200, 300] [100, 200, 300]


### 2.1. Định nghĩa Symbol và các phép toán hình thức (symbolic) 

In [ ]:
from sympy import Symbol
x = Symbol('x')         # Khởi tạo biến ký hiệu x
f = x + x + x + 2       # Biểu thức: x + x + x + 2
f


3*x + 2

In [ ]:
a = Symbol('Noi')
b = Symbol('Chim')
print(3*b + 7*a)

3*Chim + 7*Noi


In [ ]:
a.name

'Noi'

In [ ]:
b.name

'Chim'

### Một khi biểu tượng (symbol) được định nghĩa, chúng ta có thể sử dụng các phép xử lý toán học
### trên nó, như +,-,*,/ và ** (mũ). Ví dụ: 

In [3]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
s 

2*x*y

In [8]:
p = x*(x+2*x)
p

3*x**2

### SymPy sẽ tự động tạo các phép tính toán cộng và nhân. Tuy vậy, với các phép toán phức tạp hơn
### hoặc không mang đặc trưng, các công thức sẽ không thay đổi. Ví dụ: 

In [9]:
p = (x+2)*(y+3)
p
(x + 2)*(y + 3)
p = (x+2)*(y+3) + (x+2)*(x-3)
p

(x - 3)*(x + 2) + (x + 2)*(y + 3)

### Mặc dù chúng ta mong muốn biểu thức được SymPy tính toán, tuy vậy, biểu thức sẽ giống như
### những gì chúng ta nhập vào. SymPy tự động đơn giản hóa biểu thức khi chúng thực sự là đơn
### giản. Ví dụ:

In [10]:
p = x*(-x+2*x-x)
p

0

### Do đó, đối với các biểu thức phức tạp, chúng ta phải có lệnh cụ thể. Ví dụ: lệnh expand() để triển
### khai biểu thức, giả định p = (x+2)*(y+3): 

In [11]:
p = (x+2)*(y+3)
p.expand() 

x*y + 3*x + 2*y + 6

### 2.2.1. Đặt nhân tử chung và khai triển biểu thức

Hàm factor() được sử dụng khi chúng ta import thư viện factor từ gói sympy

In [12]:
from sympy import factor
bieuthuc = x**3 - y**3
factor(bieuthuc) 

(x - y)*(x**2 + x*y + y**2)

### Tương tự, để sử dụng hàm expand, chúng ta phải import thư viện expand từ gói sympy 


In [13]:
from sympy import expand
bieuthuc = (x - y)*(x**2 + x*y + y**2)
expand(bieuthuc) 

x**3 - y**3

### 2.2.3. Thay thế giá trị 

Phần này giới thiệu về cách thức sử dụng SymPy thay thế giá trị vào biểu thức đại số. Khi thay
thế giá trị của các biến, chúng ta có thể tính được giá trị của biểu thức.
Ví dụ với biểu thức 
 −  + 
, được định nghĩa bằng Sympy như sau:

In [14]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc 

x**2 - x*y + y**2

### Sau đó, chúng ta có thể tính giá trị biểu thức bằng cách thay thế cụ thể giá trị của x và y. Ví dụ:
### chúng ta thay x = 3 và y = 2 vào biểu thức trên bằng lệnh subs() như sau: 

In [ ]:
giatri = bieuthuc.subs({x:3, y:2})
giatri

x

### Tham số trong hàm subs() là liệt kê các biến sẽ được thay thế và giá trị thay thế dưới dạng cấu
### trúc từ điển (dict) của Python. Tuy nhiên, lưu ý rằng, sau khi thay thế bằng lệnh subs(), giá trị x
### và y vẫn không thay đổi do phép thay thế chỉ thay thế biến x và y trong biểu thức chứ không phải
### thay thế giá trị của x và y toàn cục. Cụ thể: 

In [21]:
giatri = bieuthuc.subs({x:3, y:2})
x

x

In [22]:
giatri = bieuthuc.subs({x:3, y:2})
y

y

```Thực hành``` : Sinh viên thực hành 3 tình huống sau:

**Tình huống 1** : Xác định theo thứ tự x=3 và y = x

In [23]:
giatri = bieuthuc.subs({x:3, y:x})
giatri

x**2 - 3*x + 9

**Tình huống 2**: Xác định theo thứ tự: x=y và y = 3 

In [24]:
giatri = bieuthuc.subs({x:y, y:3})
giatri 

9

**Tình huống 3**: Xác định y=x và sau đó tính x = 3

In [25]:
giatri = bieuthuc.subs({y:x}).subs({x:3})
giatri

9

### Sau khi thay thế, chúng ta có thể sử dụng lệnh simplify() để làm “gọn lại” biểu thức. Lệnh
### simplify() nằm trong lớp simplify của thư viện sympy, do đó, chúng ta phải import vào. Ví dụ:

In [26]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc
x**2 - x*y + y**2
bieuthuc_moi = bieuthuc.subs({x:1-y}) #  x được thay thế bằng (1-y)
bieuthuc_moi

y**2 - y*(1 - y) + (1 - y)**2

In [27]:
from sympy import simplify
dongian = simplify(bieuthuc_moi)
dongian

3*y**2 - 3*y + 1

### Hàm simplify() có thể đơn giản hóa các biểu thức phức tạp như các biểu thức về logarit và các
### biểu thức lượng giác. Ví dụ:

In [28]:
from sympy import Symbol
from sympy import sin, cos
x = Symbol('x')
y = Symbol('y')
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
bt_moi 

sin(x + y)

### 3.1. Một số lệnh cơ bản numpy xử lý vector

Khác với kiểu danh sách (list) ở Python chuẩn, numpy hỗ trợ việc định nghĩa một vector theo
nghĩa đại số:

In [31]:
import numpy as np
vec1 = np.array([1., 3., 5.])
vec1 * 2 

array([ 2.,  6., 10.])

In [33]:
vec1 * vec1 # Phép nhân từng phần tử tương ứng với nhau (phép nhân Hadamard hoặc nhân phần tử - element-wise multiplication).

array([ 1.,  9., 25.])

In [34]:
vec1 / 2

array([0.5, 1.5, 2.5])

In [35]:
vec1 + vec1


array([ 2.,  6., 10.])

In [ ]:
vec2 = np.array([2., 4.])
vec1 + vec2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

*Phép cộng vector trong numpy yêu cầu hai vector phải cùng kích thước hoặc có thể broadcast được.*

*Ở đây, kích thước khác nhau, không thể broadcast nên sẽ báo lỗi*

In [40]:
vec3 = np.array([2., 4., 6.])
vec1 + vec3 

array([ 3.,  7., 11.])

In [41]:
vec1 / vec3 

array([0.5       , 0.75      , 0.83333333])

In [42]:
vec1 * vec3 

array([ 2., 12., 30.])

In [43]:
2* vec1 + 5* vec3 

array([12., 26., 40.])

### Lưu ý:
### Trong numpy, kiểu dữ liệu vector có tên là array là kiểu dữ liệu có kích thước không thay đổi và
### chỉ 1 kiểu dữ liệu cho toàn bộ vector. Tuy vậy, một số nét tương đồng giữa kiểu dữ liệu list trong
### python và vector (array) trong Python là:
- Truy xuất đến phần tử của vector: 

In [48]:
vec3[2] 

6.0

- Tạo vector thông qua câu lệnh linspace(phần tử đầu, phần tử cuối, số lượng phần tử): 


In [49]:
vec4 = np.linspace(0, 20, 5)
vec4 

array([ 0.,  5., 10., 15., 20.])

### Ngoài ra, cách thức để tạo nhanh các vector như sau:
- Tạo các vector toàn 0:

In [54]:
vec5 = np.zeros(5)
vec5

array([0., 0., 0., 0., 0.])

- Tạo các vector toàn 1: 

In [55]:
vec6 = np.ones(5)
vec6

array([1., 1., 1., 1., 1.])

- Tạo vector ảo (giá trị rỗng): 

In [61]:
vec7 = np.empty(5)
vec7

array([1., 1., 1., 1., 1.])

- Tạo vector các giá trị ngẫu nhiên từ 0 đến 1: 

In [ ]:
np.random.random(5) # do lệnh np.rand(5) lỗi

array([0.03165229, 0.17503633, 0.84852351, 0.27250362, 0.85124314])

**Các lệnh xử lý:**
*Các lệnh dưới đây sử dụng lệnh khai báo vector v như sau:*

In [66]:
v = np.array([1., 3., 5.]) 

- Lệnh lấy tổng các thành phần của vector:

In [67]:
np.sum(v)

9.0

- Lệnh xem số chiều của một vector:

In [68]:
v.shape

(3,)

- Thử nghiệm “chuyển vị” vector: 


In [69]:
v.transpose() 

array([1., 3., 5.])

- Lệnh lấy một phần của vector: 

In [70]:
v1 = v[:2]
v1 

array([1., 3.])

In [71]:
v[0] = 5
v 

array([5., 3., 5.])

In [72]:
v1

array([5., 3.])

In [ ]:
v1[:2] = [1., 2., 3.] # Kết quả sẽ bị lỗi 


In [75]:
v1[:2] = [1., 2]
v 

array([1., 2., 5.])

### Tuy nhiên, lưu ý với các phép gán có sử dụng các toán tử: 

In [77]:
v3 = 2 * v[:2] + v1 * 3 
v3

array([ 5., 10.])

In [82]:
v1 = [4, 6]
v3

array([ 5., 10.])

In [83]:
v

array([1., 2., 5.])

- Các phép toán trên vector: trên vector, chúng ta có thể thực hiện phép toán như: lấy
sin/cos:

In [ ]:
 v + 10.0

array([11., 12., 15.])

In [85]:
np.sqrt(v) 

array([1.        , 1.41421356, 2.23606798])

In [86]:
np.cos(v)

array([ 0.54030231, -0.41614684,  0.28366219])

In [87]:
np.sin(v)

array([ 0.84147098,  0.90929743, -0.95892427])

- Tích vô hướng của hai vector (kết quả là một số): 


In [ ]:
v1 = np.array([1, 2])
v3 = np.array([3, 4])


In [89]:
np.dot(v1, v3)

11

In [90]:
v1.dot(v3)

11

In [91]:
v3.dot(v1)

11

# BÀI TẬP CHƯƠNG 1

**Bài tập 1: Giải phương trình với Sympy**

In [92]:
from sympy import Symbol, solve
x = Symbol('x')
bieuthuc = x + 3 - 5
solve(bieuthuc)

[2]

In [93]:
bieuthuc = x**2 + 3 - 5
nghiemx = solve(bieuthuc)
nghiemx

[-sqrt(2), sqrt(2)]

In [94]:
nghiemx[0]

-sqrt(2)

In [95]:
nghiemx[1]

sqrt(2)

**Bài tập 2: Giải phương trình bậc 2**

In [96]:
from sympy import solve
x = Symbol('x')
ptb2 = x**2 + 9*x +8
solve(ptb2, dict = True)

[{x: -8}, {x: -1}]

In [97]:
ptb2 = x**2 + 1*x + 10
nghiemx = solve(ptb2, dict = True)
nghiemx 

[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]

**Bài tập 3: Giải phương trình 1 biến biểu diễn đại số các biến còn lại**

In [98]:
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
ptb2 = a*x*x + b*x + c
nghiem = solve(ptb2, x, dict=True)
nghiem 

[{x: (-b - sqrt(-4*a*c + b**2))/(2*a)}, {x: (-b + sqrt(-4*a*c + b**2))/(2*a)}]

**Bài tập 4: Giải hệ phương trình**

In [99]:
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = 2*x+3*y-12
pt2 = 3*x-2*y-5 

### Sau đó, chúng ta giải hệ phương trình bằng cách thiết lập một bộ (tuple) gồm 2 phương trình trên
### ở tham số đầu tiên của lệnh solve()

In [100]:
solve((pt1, pt2), dict=True) 

[{x: 3, y: 2}]

### Để thử lại bộ nghiệm trên, nghĩa là bộ (x, y), làm cho từng phương trình của hệ có giá trị 0,
### chúng ta có lệnh lấy từng nghiệm và thay thế vào từng phương trình trên. Dưới đây là lệnh:

In [101]:
nghiem = solve((pt1, pt2), dict=True)
nghiem = nghiem[0]
pt1.subs({x:nghiem[x], y:nghiem[y]}) 

0

In [103]:
pt2.subs({x:nghiem[x], y:nghiem[y]}) 

0

**Bài tập 5: Thể hiện ma trận bằng numpy**

In [106]:
import numpy as np
M1 = np.array([ [9, 12], [23,30] ])
M1

array([[ 9, 12],
       [23, 30]])

In [107]:
u = np.array([ 2, 1])
tichM1u = M1.dot(u)
print(tichM1u) 

[30 76]


In [108]:
tichuM1 = u.dot(M1)
print(tichuM1) 

[41 54]


In [109]:
np.dot(M1, u) 

array([30, 76])

In [110]:
np.dot(u, M1) 

array([41, 54])

Sinh viên thực hành và cho biết kết quả các lệnh sau: 

In [112]:
mat1 = np.zeros( [5,5])
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
mat2 = np.ones( [5,5]) 
mat2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
mat3 = mat1 + 2* mat2
mat3

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [119]:
mat4 = mat3
mat3[3][2] = 10

mat3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [120]:
mat4

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

*Gán mat4 = mat3 không tạo bản sao mới, chỉ là tham chiếu cùng vùng nhớ*

In [125]:
mat5 = np.copy(mat3)
mat3[3][2] = 10
mat3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [127]:
mat4

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [126]:
mat5

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [129]:
mat6 = np.empty([4, 5])
mat6

array([[6.95170138e-310, 6.95170138e-310, 9.90175245e-312,
        2.33644129e-307, 9.90175245e-312],
       [1.78019082e-306, 9.90175245e-312, 6.23057348e-307,
        0.00000000e+000, 9.90175245e-312],
       [9.90175245e-312, 9.90175245e-312, 0.00000000e+000,
        8.08291397e-321, 6.64024228e-321],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [130]:
mat7 = np.identity(4)
mat7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
mat8 = np.random.random([4,5])
mat8

array([[0.63852817, 0.3978377 , 0.78495826, 0.44930288, 0.10799205],
       [0.12522946, 0.60361573, 0.58115049, 0.53946412, 0.49525738],
       [0.53398054, 0.01682574, 0.10044395, 0.63025479, 0.48432827],
       [0.21244408, 0.74178635, 0.76518547, 0.64664375, 0.39244214]])

**Bài tập 6: Tìm chỗ đóng quân:**

In [132]:
import numpy as np

# Khởi tạo các ma trận nguy cơ
A = np.array([[3, 1, 0, 0, 1],
              [0, 0, 1, 2, 3],
              [2, 1, 2, 0, 0],
              [0, 0, 2, 3, 3],
              [2, 2, 0, 0, 0]])

B = np.array([[0, 0, 0, 0, 0],
              [1, 2, 1, 0, 0],
              [2, 1, 0, 0, 0],
              [1, 1, 1, 1, 1],
              [0, 0, 0, 0, 0]])

C = np.array([[1, 0, 0, 1, 0],
              [2, 1, 0, 2, 0],
              [0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0]])

D = np.array([[0, 0, 0, 0, 0],
              [0, 0, 1, 2, 2],
              [1, 0, 0, 0, 1],
              [1, 1, 2, 1, 1],
              [1, 2, 1, 0, 0]])

E = np.array([[3, 1, 1, 0, 1],
              [0, 0, 0, 0, 0],
              [0, 0, 2, 1, 0],
              [1, 0, 1, 1, 0],
              [0, 0, 0, 0, 0]])

# Ánh xạ cấp độ sang điểm số theo bảng nguy cơ
scale = np.array([0, 1, 2, 3, 5])

# Tính điểm nguy cơ cho từng loại theo từng ô
danger_A = scale[A]
danger_B = scale[B]
danger_C = scale[C]
danger_D = scale[D]
danger_E = scale[E]

# Tổng nguy cơ tại từng ô
total_risk = danger_A + danger_B + danger_C + danger_D + danger_E

# Tìm các vị trí an toàn (tổng nguy cơ ≤ 5)
safe_positions = total_risk <= 5

print("Tổng nguy cơ:")
print(total_risk)

print("\nVị trí an toàn để đóng quân (True = an toàn):")
print(safe_positions)


Tổng nguy cơ:
[[7 2 1 1 2]
 [3 3 3 6 5]
 [5 2 4 1 1]
 [3 2 6 7 5]
 [3 4 1 1 0]]

Vị trí an toàn để đóng quân (True = an toàn):
[[False  True  True  True  True]
 [ True  True  True False  True]
 [ True  True  True  True  True]
 [ True  True False False  True]
 [ True  True  True  True  True]]
