## CHƯƠNG 2: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH 

Hàm “scale” tỉ số vector bằng một giá trị thực

In [5]:
def scale(a, v):
    return [a * vi for vi in v]

v = [3, 5, 7]
print(scale(10, v))


[30, 50, 70]


Hàm lấy tổng hai vector

In [6]:
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]

v = [3, 5, 7]
w = [2, 4, 6]
print(sumvector(v, w))


[5, 9, 13]


Hàm nhân 2 vector vô hướng

In [7]:
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

v = [3, 5, 7]
w = [2, 4, 6]

print(dotvector(v, w))


68


Hàm tính chiều dài một vector

In [8]:
import math

def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

def lenvector(v):
    return math.sqrt(dotvector(v, v))

w = [2, 4, 6]
print(lenvector(w))


7.483314773547883


## 2. Bài toán ứng dụng 1 – Phân loại tuyến tính 

scores  = np.array([-1, 1, 2, -3, 5, -4]) 

In [12]:
import numpy as np

scores = np.array([-1, 1, 2, -3, 5, -4])
scores

array([-1,  1,  2, -3,  5, -4])

scores >= 0 

In [22]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0

array([False,  True,  True, False,  True, False])

scores < 0 

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores < 0

array([ True, False, False,  True, False,  True])

np.select([scores >=0, scores < 0],[‘so duong’, ‘so am’])

In [19]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
np.select([scores >= 0, scores < 0], ['so duong', 'so am'])

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

Kết quả câu lệnh bên trên là phương cách phân loại dữ liệu, theo đó, lệnh select phân thành 2 
loại. Ví dụ dưới đây cho ta thấy lệnh np.select có thể phân loại thành 3 loại: 
- scores  = np.array([-1, 1, 2, 0, -3, 5, 0, -4]) 
- np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am']) 

In [21]:
import numpy as np
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

## 3. Thực hành xử lý ma trận 

### 3.1. Cơ bản về xử lý ma trận 

In [23]:
import numpy as np
from scipy import linalg, sparse

D = np.mat([[3, 4], [5, 6]])

print(D)

[[3 4]
 [5 6]]


np.mat(np.random.random((5,7))) 

In [24]:
>>> import numpy as np
>>> C = np.mat(np.random.random((5,7)))
>>> print(C)

[[0.56028053 0.46016031 0.6330855  0.33707305 0.65590929 0.08189306
  0.32552204]
 [0.28815452 0.41142222 0.06935001 0.19700567 0.48285351 0.13907847
  0.43352419]
 [0.06941871 0.27189816 0.38749818 0.35437002 0.92283195 0.23912146
  0.98743797]
 [0.57149369 0.50957954 0.61581728 0.74290084 0.71531319 0.97045777
  0.11431383]
 [0.9040757  0.61291823 0.56747806 0.91454154 0.98331908 0.00707639
  0.38170193]]


np.mat(np.random.random((2,2))) 

In [26]:
import numpy as np
A = np.mat(np.random.random((2,2)))
print(A)

[[0.95421309 0.82288065]
 [0.52802018 0.5720733 ]]


 b = np.array([(1+5j, 2j, 3j),(4, 5, 6)]) 

In [ ]:
import numpy as np
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)
print(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


A.T

In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])  # Ma trận 2x3
A_transposed = A.T  # Hoặc np.transpose(A)
print("Ma trận gốc:")
print(A)
print("\nMa trận chuyển vị:")
print(A_transposed)

Ma trận gốc:
[[1 2 3]
 [4 5 6]]

Ma trận chuyển vị:
[[1 4]
 [2 5]
 [3 6]]


linalg.inv(A) 

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])  # Ma trận vuông 2x2
A_inv = np.linalg.inv(A)  # Hoặc A.I nếu A là np.matrix
print("Ma trận nghịch đảo:")
print(A_inv)

Ma trận nghịch đảo:
[[-2.   1. ]
 [ 1.5 -0.5]]


M = np.array([[-1,3,2],[0,2,1],[1,5,-2]]) 

In [ ]:
import numpy as np
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_lower = np.tril(M)  
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [ ]:
import numpy as np
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_upper = np.triu(M)  # Lấy phần tam giác trên (bao gồm cả đường chéo)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [44]:
 import numpy as np
 M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])

 v_diag = np.diag(M)
 print("Vector đường chéo:")
 print(v_diag)

 M_diag = np.diag(v_diag)
 print("\nMa trận đường chéo:")
 print(M_diag)

Vector đường chéo:
[-1 -2 -2]

Ma trận đường chéo:
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


### Thực hiện tính toán đơn giản trên ma trận 

In [33]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x**2+2-6, y-1-6, x+z-1, 2*x**2-8, z**2+4-5, y-z-8], [x, y, z])

[(2, 7, -1)]

In [34]:
x = [1, 2, 3]
y = [1, 2, 3]
print(all([x[i]==y[i] for i in range(len(x))]))  
y = [1, 2, 4]
print(all([x[i]==y[i] for i in range(len(x))]))  

True
False


In [35]:
import numpy as np
np.array_equal([1, 2], [1, 2])  
np.array_equal(np.array([1, 2]), np.array([1, 2]))  

True

### 3.2. Các phép biến đổi sơ cấp trên ma trận

In [36]:
import numpy as np

A = np.reshape(np.arange(0, 36), (6,6))
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


I6 = np.identity(6) 
print I6 

In [37]:
import numpy as np

I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Sau đó, xem lại kích thước của ma trận (số lượng phần tử) và in đường chéo của ma trận A: 
A.size 

In [38]:
import numpy as np

A = np.reshape(np.arange(0, 36), (6, 6))
print(A.size)

36


np.matrix.diagonal(A) 

In [39]:
import numpy as np

A = np.reshape(np.arange(0, 36), (6, 6))
print(np.diagonal(A))

[ 0  7 14 21 28 35]


Thành lập ma trận  mới bằng công thức = + 
 A = A + I6 
 print A

In [40]:
import numpy as np

A = np.reshape(np.arange(0, 36), (6, 6))
I6 = np.identity(6)
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Tính tích (nhân) ma trận với vector (là dạng ma trận đặc biệt): 

In [42]:
import numpy as np

A = np.array([[1, 1, 2, 3, 4, 5],
              [6, 8, 8, 9, 10, 11],
              [12, 13, 15, 15, 16, 17],
              [18, 19, 20, 22, 22, 23],
              [24, 25, 26, 27, 29, 29],
              [30, 31, 32, 33, 34, 36]])
vecB = np.array([1, 2, 3, 4, 5, 6])
C = A.dot(vecB)
print(C)

[ 71 198 325 452 579 706]


Khai báo ma trận D 2x6 


In [43]:
import numpy as np

D = np.array([[1, 2, 3, 4, 5, 6], [1, 0, 1, 0, 1, 0]])
print(D)

[[1 2 3 4 5 6]
 [1 0 1 0 1 0]]


Tính tích ma trận A và D: × 

In [47]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5],
              [6, 8, 9, 10, 11],
              [12, 13, 15, 16, 17],
              [18, 19, 20, 22, 23],
              [24, 25, 26, 27, 29],
              [30, 31, 32, 33, 36]])
D = np.array([[1, 2, 3, 4, 5, 6], [1, 0, 1, 0, 1, 0]])
E = A.dot(D.T)  
print(E)

ValueError: shapes (6,5) and (6,2) not aligned: 5 (dim 1) != 6 (dim 0)

Xây dựng ma trận F kích thước 6x2: 

In [48]:
import numpy as np

A = np.array([[1, 1, 2, 3, 4, 5],
              [6, 8, 8, 9, 10, 11],
              [12, 13, 15, 15, 16, 17],
              [1, 1, 2, 3, 4, 5],
              [6, 8, 8, 9, 10, 11],
              [12, 13, 15, 15, 16, 17]])
F = np.array([[1, 1], [2, 0], [3, 1], [4, 0], [5, 1], [6, 0]])
G = A.dot(F)
print(F)

[[1 1]
 [2 0]
 [3 1]
 [4 0]
 [5 1]
 [6 0]]


print G

In [49]:
import numpy as np

A = np.array([[1, 1, 2, 3, 4, 5],
              [6, 8, 8, 9, 10, 11],
              [12, 13, 15, 15, 16, 17],
              [18, 19, 20, 22, 22, 23],
              [24, 25, 26, 27, 29, 29],
              [30, 31, 32, 33, 34, 36]])
F = np.array([[1, 1], [2, 0], [3, 1], [4, 0], [5, 1], [6, 0]])
G = A.dot(F)
print(G)

[[ 71   7]
 [198  24]
 [325  43]
 [452  60]
 [579  79]
 [706  96]]


Tính ma trận nghịch đảo: 
np.linalg.inv(A)

In [50]:
import numpy as np

A = np.array([[1, 1, 2, 3, 4, 5],
              [6, 8, 8, 9, 10, 11],
              [12, 13, 15, 15, 16, 17],
              [18, 19, 20, 22, 22, 23],
              [24, 25, 26, 27, 29, 29],
              [30, 31, 32, 33, 34, 36]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


##  4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng! 


In [51]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
print(b) 

[89 55]


## 5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa


### 5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm


In [52]:
import sympy as sp
from sympy import Symbol
17
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [53]:
# Bài tập: Sinh viên thử bằng phương pháp nhân ma trận:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])

In [54]:
A_nghichdao = np.linalg.inv(A)

LinAlgError: Singular matrix

## BÀI TẬP CHƯƠNG 2

In [55]:
#van de 1

import numpy as np

A = np.array([[1, -1],
              [2,  3]])
B = np.array([-2, 6])

x = np.linalg.solve(A, B)
print("Giao điểm:", x)

Giao điểm: [0. 2.]


In [57]:
#van de 2

A = np.array([[ 1, -1,  0],
              [ 2, -1, -1],
              [ 1,  1,  1]])
B = np.array([2, 3, 6])

x = np.linalg.solve(A, B)
print("Giao điểm:", x)

Giao điểm: [3. 1. 2.]


In [ ]:
#van de 3

A = np.array([[1, 1, 1],
              [4, 2, 1],
              [9, 3, 1]])
B = np.array([4, 4, 4])

x = np.linalg.solve(A, B)
print("Hệ số đa thức [a, b, c]:", x)

In [ ]:
#van de 4

A = np.array([[1, 0, 1],
              [1, 1, -2],
              [-2, 2, 1]])
B = np.array([1, -3, 0])

x = np.linalg.solve(A, B)
print("Hệ số [a, b, c]:", x)

Câu 2

In [58]:
#van de 1

x, y = sp.symbols('x y')

eq1 = sp.Eq(x - y, -2)
eq2 = sp.Eq(2*x + 3*y, 6)

solution = sp.solve((eq1, eq2), (x, y))
print(solution)

{x: 0, y: 2}


In [ ]:
# Vấn đề 2
x, y, z = sp.symbols('x y z')

eq1 = sp.Eq(x - y, 2)
eq2 = sp.Eq(2*x - y - z, 3)
eq3 = sp.Eq(x + y + z, 6)

solution = sp.solve((eq1, eq2, eq3), (x, y, z))
print(solution)

In [ ]:
# Vấn đề 3 
a, b, c = sp.symbols('a b c')

eq1 = sp.Eq(a + b + c, 4)       # p(1)
eq2 = sp.Eq(4*a + 2*b + c, 4)   # p(2)
eq3 = sp.Eq(9*a + 3*b + c, 4)   # p(3)

solution = sp.solve((eq1, eq2, eq3), (a, b, c))
print(solution)

In [ ]:
# Vấn đề 4 
a, b, c = sp.symbols('a b c')

eq1 = sp.Eq(a + c, 1)
eq2 = sp.Eq(a + b - 2*c, -3)
eq3 = sp.Eq(-2*a + 2*b + c, 0)

solution = sp.solve((eq1, eq2, eq3), (a, b, c))
print(solution)

Câu 3

In [59]:
import numpy as np

def fibonacci_matrix(k):
    F = np.array([[1, 1],
                  [1, 0]], dtype=object)
    result = np.linalg.matrix_power(F, k)
    return result

# Kiểm tra với k = 5 (F_5)
k = 5
Fk = fibonacci_matrix(k)
print("F_{} =\n{}".format(k, Fk))

# So sánh với Fibonacci thật
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

print("Fib(k+1) =", fib(k+1))
print("Fib(k)   =", fib(k))
print("Fib(k-1) =", fib(k-1))

F_5 =
[[8 5]
 [5 3]]
Fib(k+1) = 8
Fib(k)   = 5
Fib(k-1) = 3
