## CHƯƠNG 3: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

In [1]:
from scipy import linalg   # Tải gói linalg của scipy vào bộ nhớ (để sử dụng) 
import numpy as np      
# Tải gói numpy vào sử dụng với tên gọi là np 
a = np.array([1, 2, 3]) 
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức 
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực 
A = np.matrix(np.random.random( (2,2) ) ) 
B = np.asmatrix(b)  # Chuyển b thành dạng ma trận 
C = np.mat(np.random.random( (10,5) ) ) 
D = np.mat([  [4, 3], [2, 6] ]) 
F = np.eye(3, k=1)

In [2]:
A

matrix([[0.4799783 , 0.38314771],
        [0.12927295, 0.50137979]])

In [3]:
B

matrix([[1.+9.j, 0.+2.j, 0.+3.j],
        [0.+4.j, 0.+5.j, 0.+6.j]])

In [4]:
C

matrix([[0.82350455, 0.27018323, 0.35292764, 0.75248886, 0.07300228],
        [0.17584013, 0.4350951 , 0.11147608, 0.76960569, 0.61390631],
        [0.8021917 , 0.13589102, 0.13042905, 0.91447705, 0.15063828],
        [0.35086273, 0.26579422, 0.97321624, 0.97172603, 0.4508848 ],
        [0.09644824, 0.01642133, 0.04227612, 0.93244464, 0.71755718],
        [0.60589262, 0.74115331, 0.59608137, 0.2518184 , 0.02862137],
        [0.96786532, 0.73474014, 0.54468715, 0.67419017, 0.75351048],
        [0.33216033, 0.87518047, 0.5968576 , 0.97428601, 0.63521596],
        [0.52379484, 0.64413999, 0.54645633, 0.68309215, 0.57063941],
        [0.70094453, 0.1353594 , 0.52595032, 0.1182716 , 0.96834999]])

In [5]:
D

matrix([[4, 3],
        [2, 6]])

In [6]:
F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [9]:
F = np.eye(3, k=0)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
F = np.eye(3, k=-1)  
F

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

### Các phép xử lý đơn giản 

In [11]:
np.linalg.matrix_rank(C)

5

In [13]:
#Tính ma trận nghịch đảo

A

matrix([[0.4799783 , 0.38314771],
        [0.12927295, 0.50137979]])

In [15]:
A.I 

matrix([[ 2.62336609, -2.00474116],
        [-0.67639396,  2.5113872 ]])

In [18]:
linalg.inv(A)

array([[ 2.62336609, -2.00474116],
       [-0.67639396,  2.5113872 ]])

In [19]:
A.T

matrix([[0.4799783 , 0.12927295],
        [0.38314771, 0.50137979]])

In [20]:
A.H

matrix([[0.4799783 , 0.12927295],
        [0.38314771, 0.50137979]])

In [21]:
#Giải các loại phương trình tuyến tính: 

linalg.solve(A, b) 

array([[ 2.62336609+15.59133021j,  0.         -4.77697361j,
         0.         -4.15834868j],
       [-0.67639396 +3.95800316j,  0.        +11.20414809j,
         0.        +13.03914134j]])

In [23]:
E = np.mat(a).T 
E

matrix([[1],
        [2],
        [3]])

In [24]:
linalg.lstsq(F, E) 

(array([[2.],
        [3.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

Các hàm trên ma trận 

Giới thiệu một số hàm trên ma trận. Các bạn sinh viên thực tập trên ma trận A và D khai 
báo bên trên: 

In [ ]:
# Cộng ma trận:

np.add(A, D)


matrix([[4.4799783 , 3.38314771],
        [2.12927295, 6.50137979]])

In [28]:
#Trừ ma trận:
  
np.subtract(A, D) 

matrix([[-3.5200217 , -2.61685229],
        [-1.87072705, -5.49862021]])

In [29]:
#Chia ma trận:

np.divide(A, D) 

matrix([[0.11999457, 0.1277159 ],
        [0.06463647, 0.0835633 ]])

In [30]:
# Nhân ma trận:
 
A @ D   # phiên bản Python 3.x 

matrix([[2.68620861, 3.73882115],
        [1.51985137, 3.3960976 ]])

In [31]:
np.multiply(D, A) 

matrix([[1.9199132 , 1.14944313],
        [0.25854589, 3.00827876]])

In [32]:
np.dot(A, D) 

matrix([[2.68620861, 3.73882115],
        [1.51985137, 3.3960976 ]])

In [33]:
np.vdot(A, D) 

matrix([[1.9199132]])

In [34]:
#Hàm lũy thừa và logarith ma trận:
 
linalg.expm(A) 

array([[1.65651499, 0.63103426],
       [0.21290917, 1.69176269]])

In [35]:
linalg.logm(A) 

array([[-0.85094981,  0.84232847],
       [ 0.28419923, -0.80389984]])

## 2.3. Ma trận hội tụ 

In [36]:
A = np.array([[0, 1], [1, 0]])
print(A)

[[0 1]
 [1 0]]


In [37]:
temp = A.dot(A)     # tính toan lần thứ 1 
print(temp) 

[[1 0]
 [0 1]]


In [39]:
import numpy as np

A = np.array([[0, 1],
              [1, 0]]) 
k = 6

temp = A.copy()

for i in range(k - 1):
    temp = temp.dot(A)
    print(temp)
    print('---')


[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---


In [40]:
B = np.array([ [0,-1], [-1,0]]) 
print(B) 

[[ 0 -1]
 [-1  0]]


In [41]:
temp = B.dot(B)     # tính toan lần thứ 1 
print(temp)

[[1 0]
 [0 1]]


In [43]:
import numpy as np

B = np.array([[1, 2],
              [3, 4]])

k = 5

temp = B.copy()

for i in range(k - 1):
    temp = temp.dot(B)
    print(temp)
    print('---')

[[ 7 10]
 [15 22]]
---
[[ 37  54]
 [ 81 118]]
---
[[199 290]
 [435 634]]
---
[[1069 1558]
 [2337 3406]]
---


In [45]:
# Ma trận hội tụ - Convergent matrix: 

C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ]) 
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [46]:
temp = C.dot(C)     # tính toan lần thứ 1 
print(temp) 

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [48]:
import numpy as np

C = np.array([[1, 2],
              [3, 4]])

k = 1000

temp = C.copy()

for i in range(k - 1):
    temp = temp.dot(C)
    print(temp)


[[ 7 10]
 [15 22]]
[[ 37  54]
 [ 81 118]]
[[199 290]
 [435 634]]
[[1069 1558]
 [2337 3406]]
[[ 5743  8370]
 [12555 18298]]
[[30853 44966]
 [67449 98302]]
[[165751 241570]
 [362355 528106]]
[[ 890461 1297782]
 [1946673 2837134]]
[[ 4783807  6972050]
 [10458075 15241882]]
[[25699957 37455814]
 [56183721 81883678]]
[[138067399 201223170]
 [301834755 439902154]]
[[  741736909  1081027478]
 [ 1621541217 -1931689170]]
[[-310147953 1512616434]
 [ 121441003 -188706950]]
[[ -67265947 1135202534]
 [-444679847 -511945794]]
[[ -956625641   111310946]
 [-1980517229  1357824426]]
[[ -622692803 -1468007498]
 [ 2092956049  1470263246]]
[[ -731748001  1472518994]
 [-2086188805  1477030490]]
[[ -609158315   131612678]
 [-1950064631  1735744350]]
[[ -214320281  -691865918]
 [-1037798877 -1252119158]]
[[2005049261 1098863062]
 [-499189055 1505860206]]
[[1006671151 -184383822]
 [-276575733  730095418]]
[[  453519685  1275807014]
 [ 1913710521 -1927737090]]
[[ -14026569 1715300130]
 [ 425466547  411439978]]

In [50]:
k = 1000
temp = C.copy()      

for i in range(k-1):
    temp = temp.dot(C)
    print(temp)


[[ 7 10]
 [15 22]]
[[ 37  54]
 [ 81 118]]
[[199 290]
 [435 634]]
[[1069 1558]
 [2337 3406]]
[[ 5743  8370]
 [12555 18298]]
[[30853 44966]
 [67449 98302]]
[[165751 241570]
 [362355 528106]]
[[ 890461 1297782]
 [1946673 2837134]]
[[ 4783807  6972050]
 [10458075 15241882]]
[[25699957 37455814]
 [56183721 81883678]]
[[138067399 201223170]
 [301834755 439902154]]
[[  741736909  1081027478]
 [ 1621541217 -1931689170]]
[[-310147953 1512616434]
 [ 121441003 -188706950]]
[[ -67265947 1135202534]
 [-444679847 -511945794]]
[[ -956625641   111310946]
 [-1980517229  1357824426]]
[[ -622692803 -1468007498]
 [ 2092956049  1470263246]]
[[ -731748001  1472518994]
 [-2086188805  1477030490]]
[[ -609158315   131612678]
 [-1950064631  1735744350]]
[[ -214320281  -691865918]
 [-1037798877 -1252119158]]
[[2005049261 1098863062]
 [-499189055 1505860206]]
[[1006671151 -184383822]
 [-276575733  730095418]]
[[  453519685  1275807014]
 [ 1913710521 -1927737090]]
[[ -14026569 1715300130]
 [ 425466547  411439978]]

In [51]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]]) 
MM = M.dot(M)   
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [52]:
MM = M.dot(M)   # tính M3 
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [54]:
import numpy as np
M = np.array([[1, 2],
              [3, 4]])

MM = M.copy()

for i in range(100):
    MM = MM.dot(M)
    print(MM)


[[ 7 10]
 [15 22]]
[[ 37  54]
 [ 81 118]]
[[199 290]
 [435 634]]
[[1069 1558]
 [2337 3406]]
[[ 5743  8370]
 [12555 18298]]
[[30853 44966]
 [67449 98302]]
[[165751 241570]
 [362355 528106]]
[[ 890461 1297782]
 [1946673 2837134]]
[[ 4783807  6972050]
 [10458075 15241882]]
[[25699957 37455814]
 [56183721 81883678]]
[[138067399 201223170]
 [301834755 439902154]]
[[  741736909  1081027478]
 [ 1621541217 -1931689170]]
[[-310147953 1512616434]
 [ 121441003 -188706950]]
[[ -67265947 1135202534]
 [-444679847 -511945794]]
[[ -956625641   111310946]
 [-1980517229  1357824426]]
[[ -622692803 -1468007498]
 [ 2092956049  1470263246]]
[[ -731748001  1472518994]
 [-2086188805  1477030490]]
[[ -609158315   131612678]
 [-1950064631  1735744350]]
[[ -214320281  -691865918]
 [-1037798877 -1252119158]]
[[2005049261 1098863062]
 [-499189055 1505860206]]
[[1006671151 -184383822]
 [-276575733  730095418]]
[[  453519685  1275807014]
 [ 1913710521 -1927737090]]
[[ -14026569 1715300130]
 [ 425466547  411439978]]

### 3.2. Phân rã ma trận LU 

In [56]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]]) 
P, L, U = linalg.lu(M)    # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U 
print (P) 

[[1. 0.]
 [0. 1.]]


In [57]:
print(L)

[[1.   0.  ]
 [0.25 1.  ]]


In [58]:
print(U)

[[0.8   0.3  ]
 [0.    0.625]]


In [59]:
L.dot(U) 

array([[0.8, 0.3],
       [0.2, 0.7]])

## 5. Bài toán ứng dụng 2 – Bài toán loan tin 

In [60]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]]) 
temp = A.dot(A)    # lúc này temp =  
print(temp) 

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [61]:
temp = temp.dot(A)    # lúc này temp =  
print(temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [63]:
import numpy as np

A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

sumA = A.copy()

temp = A.dot(A)   
k = 3
sumA = sumA + temp  

for i in range(1, k - 1):
    temp = temp.dot(A)  
    sumA = sumA + temp   

print("A^3 =\n", temp)
print("\nA^1 + A^2 + A^3 =\n", sumA)


A^3 =
 [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]

A^1 + A^2 + A^3 =
 [[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


## BÀI TẬP CHƯƠNG 3 


#### Câu 1: Hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để: 


In [ ]:
#a) Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch (tồn tại ma trận nghịch đảo) 

import numpy as np
from sympy import Matrix

# a) Chọn một ma trận 3×3 khả nghịch
A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

detA = round(np.linalg.det(A))
A_sym = Matrix(A.tolist())
detA_sym = A_sym.det()

print("det(A) =", detA)         
print("det(A) (Sympy) =", detA_sym)
if detA_sym == 0:
    raise ValueError("det(A) = 0, ma trận không khả nghịch!")

A_inv_np = np.linalg.inv(A)
A_inv_sym = A_sym.inv()

print("\nA^{-1} (NumPy) =")
print(np.round(A_inv_np, 6))    
print("\nA^{-1} (Sympy) =")
print(A_inv_sym)

I_np = A.dot(A_inv_np)
I_sym = (A_sym * A_inv_sym).evalf()

print("\nA·A^{-1} (NumPy) ≈")
print(np.round(I_np, 6))
print("\nA·A^{-1} (Sympy) =")
print(I_sym)


det(A) = 1
det(A) (Sympy) = 1

A^{-1} (NumPy) =
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

A^{-1} (Sympy) =
Matrix([[-24, 18, 5], [20, -15, -4], [-5, 4, 1]])

A·A^{-1} (NumPy) ≈
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]

A·A^{-1} (Sympy) =
Matrix([[1.00000000000000, 0, 0], [0, 1.00000000000000, 0], [0, 0, 1.00000000000000]])


In [69]:
# b) Nhập họ và tên hoặc mã số sinh viên (của sinh viên). 

text = input("Nhập họ và tên hoặc mã số sinh viên: ")


In [71]:
#c) Mã hóa họ và tên hoặc mã số sinh viên (của sinh viên). 

text_bytes = [ord(char) for char in text]

while len(text_bytes) % 3 != 0:
    text_bytes.append(0) 

vectors = np.array(text_bytes).reshape(-1, 3).T  
encoded = A @ vectors

print("\nMã hóa (ma trận kết quả):")
print(encoded.astype(int))




Mã hóa (ma trận kết quả):
[[317 157]
 [260  50]
 [596 585]]


In [72]:
#d) Thực hiện giải mã với ma trận được chọn. 

decoded = np.linalg.inv(A) @ encoded

decoded_rounded = np.round(decoded).astype(int).T.flatten()
decoded_text = ''.join(chr(num) for num in decoded_rounded if num != 0)

print("\nGiải mã:")
print(decoded_text)



Giải mã:
48392


#### Câu 2: Tính toán phân số từ liên phân số (continued fractions) 


In [ ]:
# a. Xây dựng chương trình tính


def continued_fraction(c):
    n = len(c)
    p = [0] * n
    q = [0] * n

    p[0] = c[0]
    q[0] = 1

    if n > 1:
        p[1] = c[1] * c[0] + 1
        q[1] = c[1]

    for i in range(2, n):
        p[i] = c[i] * p[i - 1] + p[i - 2]
        q[i] = c[i] * q[i - 1] + q[i - 2]

    return p[-1], q[-1] 

c = [3, 1, 2] 
pn, qn = continued_fraction(c)
print(f"Phân số: {pn}/{qn}")


Phân số: 11/3
