## CHƯƠNG 4: CƠ BẢN VỀ ĐỊNH THỨC 

In [4]:
import numpy as np

n = 4
X = np.array(range(1, n+1))
sigma = np.array([4, 3, 2, 1])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X)-1):
        for j in range(i+1, len(X)):
            ket_qua = ket_qua * ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)

sigma = np.array([2, 1, 3, 4])
sgn_by_def(sigma)

-1

In [5]:
import numpy as np

n = 4
X = np.array(range(1, n+1))
sigma = np.array([1, 2, 3, 4])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X)-1):
        for j in range(i+1, len(X)):
            ket_qua = ket_qua * ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)

sigma = np.array([1, 2, 3, 4])
sgn_by_def(sigma)

1

In [6]:
import numpy as np

n = 4
X = np.array(range(1, n+1))
sigma = np.array([4, 3, 2, 1])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X)-1):
        for j in range(i+1, len(X)):
            ket_qua = ket_qua * ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)

sigma = np.array([4, 3, 2, 1])
sgn_by_def(sigma)

1

### Định thức: 

In [7]:
from itertools import permutations

n = 3
X = []

for i in range(1, n+1):
    X.append(i)

Sn = list(permutations(X)) 
print(Sn)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [10]:
import numpy as np

def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i) + 1)
        dau = sgn_by_def(sigma)
        if (dau == 1):
            product = " + " + product
        else:
            product = " - " + product
        dinhthuc = dinhthuc + product
    return dinhthuc

def sgn_by_def(sigma):
    pass

n = 2
ketqua = phatsinh_dinhthuc(n) + " + a11a22 - a12a21"
print(ketqua)

 - a11a22 - a12a21 + a11a22 - a12a21


In [11]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    inversions = 0
    for i in range(len(sigma)):
        for j in range(i + 1, len(sigma)):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i) + 1)
        dau = sgn_by_def(sigma)
        if (dau == 1):
            product = " + " + product
        else:
            product = " - " + product
        dinhthuc = dinhthuc + product
    return dinhthuc

n = 3
ketqua = phatsinh_dinhthuc(n)
print(ketqua)

 + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31


In [12]:
import math
import numpy as np
from itertools import permutations

def tinhtoan_dinhthuc(A):
    X = []
    n = int(math.sqrt(A.size)) 
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))  
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1 
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)] 
        dau = sgn_by_def(sigma)  
        if (dau == 1):
            dinhthuc = dinhthuc + product  
        else:
            dinhthuc = dinhthuc + product * (-1) 
    return dinhthuc

def sgn_by_def(sigma):
    inversions = 0
    for i in range(len(sigma)):
        for j in range(i + 1, len(sigma)):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

A = np.array([[3, 5, 8], [4, 12, -1], [2, 5, 3]])

ketqua = tinhtoan_dinhthuc(A)
print(ketqua)

21


### 3. Quy tắc Cramer

In [13]:
import numpy as np
from scipy import linalg

A = np.array([[4, -2], [3, -5]]) 

A1 = np.array([[10, -2], [11, -5]])

A2 = np.array([[4, 10], [3, 11]])

detA = linalg.det(A)    
detA1 = linalg.det(A1)  
detA2 = linalg.det(A2) 

print(detA, detA1, detA2)

-14.0 -28.0 14.000000000000004


In [14]:
import numpy as np
from scipy import linalg

A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])
A2 = np.array([[4, 10], [3, 11]])

detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)

if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
    print("Hài nghiệm của phương trình là:", x1, x2)

Hài nghiệm của phương trình là: 2.0 -1.0000000000000002


In [15]:
import numpy as np
from itertools import permutations

def tinhtoan_dinhthuc(A):
    X = []
    n = int(np.sqrt(A.size))
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]
        dau = sgn_by_def(sigma)
        if (dau == 1):
            dinhthuc = dinhthuc + product
        else:
            dinhthuc = dinhthuc + product * (-1)
    return dinhthuc

def sgn_by_def(sigma):
    inversions = 0
    for i in range(len(sigma)):
        for j in range(i + 1, len(sigma)):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

A = np.array([[3, 5, 8], [4, 12, -1], [2, 5, 3]])
A1 = np.array([[10, 5, 8], [11, 12, -1], [2, 5, 3]])
A2 = np.array([[3, 10, 8], [4, 11, -1], [2, 5, 3]])

detA = tinhtoan_dinhthuc(A)
detA1 = tinhtoan_dinhthuc(A1)
detA2 = tinhtoan_dinhthuc(A2)

print(detA)
print(detA1)
print(detA2)

21
483
-42


### Hệ ba phương trình tuyến tính bậc 1: 


In [16]:
import numpy as np
from scipy import linalg

A = np.array([[-1, 2, -3], [2, -2, 1], [3, -4, 4]])
b = np.array([1, 3, 2])

detA = linalg.det(A)
dinhthuc = linalg.solve(A, b)

print(detA)
print(dinhthuc)

0.0
[ 1.   -1.25 -1.5 ]


C:\Users\QUOC TRONG\AppData\Local\Temp\ipykernel_18496\4113592680.py:8: LinAlgWarning: Ill-conditioned matrix (rcond=1.00929e-17): result may not be accurate.
  dinhthuc = linalg.solve(A, b)


In [17]:
import numpy as np
from scipy import linalg

A = np.array([[-1, 2, -3], [2, -2, 1], [3, -4, 4]])
b = np.array([1, 3, 2])

det = linalg.det(A)
x, y, z = linalg.solve(A, b)

print("Nghiệm của phương trình:", "x=", x, "y=", y, "z=", z)

Nghiệm của phương trình: x= 1.0 y= -1.25 z= -1.5


C:\Users\QUOC TRONG\AppData\Local\Temp\ipykernel_18496\392088771.py:8: LinAlgWarning: Ill-conditioned matrix (rcond=1.00929e-17): result may not be accurate.
  x, y, z = linalg.solve(A, b)


In [18]:
import numpy as np
from itertools import permutations

def tinhtoan_dinhthuc(A):
    X = []
    n = int(np.sqrt(A.size))
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]
        dau = sgn_by_def(sigma)
        if (dau == 1):
            dinhthuc = dinhthuc + product
        else:
            dinhthuc = dinhthuc + product * (-1)
    return dinhthuc

def sgn_by_def(sigma):
    inversions = 0
    for i in range(len(sigma)):
        for j in range(i + 1, len(sigma)):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

A = np.array([[-1, 2, -3], [2, -2, 1], [3, -4, 4]])
b = np.array([1, 3, 2])
X = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Y = np.array([[0, 2, -3], [2, 0, 1], [3, -4, 0]])
Z = np.array([[-1, 2, 0], [2, -2, 0], [3, -4, 1]])

det = tinhtoan_dinhthuc(A)
detX = tinhtoan_dinhthuc(X)
detY = tinhtoan_dinhthuc(Y)
detZ = tinhtoan_dinhthuc(Z)

x, y, z = detX/det, detY/det, detZ/det

print("Nghiệm", "x=", x, "y=", y, "z=", z)

Nghiệm x= inf y= inf z= -inf


C:\Users\QUOC TRONG\AppData\Local\Temp\ipykernel_18496\1830136583.py:44: RuntimeWarning: divide by zero encountered in scalar divide
  x, y, z = detX/det, detY/det, detZ/det


### Tính diện tích tam giác: 


In [19]:
import sympy as sp

TG = sp.Matrix([[1, 0, 1], [4, 3, 1], [2, 2, 1]])

dientich = 1/2 * abs(TG.det())

print(dientich)

1.50000000000000


### Ứng dụng 1: Tính diện tích đa giác gồm  điểm ( , ): 


In [20]:
import numpy as np

points = np.array([
    [118112.25, 602362.70],
    [1181136.18, 602366.68],
    [1181130.97, 602379.69],
    [1181125.77, 602381.91],
    [1181122.06, 602380.42]
])

x = points[:, 0]
y = points[:, 1]

n = len(points)
area = 0.0

for i in range(n):
    j = (i + 1) % n
    area += x[i] * y[j]
    area -= y[i] * x[j]

area = abs(area) / 2.0

print(area)

7303066.547859192


### Ứng dụng 2: Mở rộng bài toán tính diện tích thành thể tích hình tứ diện: 


In [21]:
import sympy as sp

M = sp.Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])

dientich = 1/6 * abs(M.det())

print(dientich)

12.0000000000000


### Ứng dụng 4: Phương trình mặt phẳng 


In [22]:
from sympy import *

x, y, z = symbols('x y z')

MP = Matrix([[x, y, z, 1], [-1, 3, 2, 1], [0, 1, 0, 1], [-2, 0, 1, 1]])

dinhthuc = MP.det()

print(dinhthuc)

-4*x + 3*y - 5*z - 3


## 5. Bài toán ứng dụng 3: Tính quỹ đạo của hành tinh/vệ tinh 


In [ ]:
from sympy import *

a, b, c, d, e, f = symbols('a b c d e f')
x, y = symbols('x y')
x1, y1, x2, y2, x3, y3, x4, y4, x5, y5 = symbols('x1 y1 x2 y2 x3 y3 x4 y4 x5 y5')

M = Matrix([[x**2, x*y, y**2, x, y, 1],
            [x1**2, x1*y1, y1**2, x1, y1, 1],
            [x2**2, x2*y2, y2**2, x2, y2, 1],
            [x3**2, x3*y3, y3**2, x3, y3, 1],
            [x4**2, x4*y4, y4**2, x4, y4, 1],
            [x5**2, x5*y5, y5**2, x5, y5, 1]])

coeffs = M.rref()[0]

print(coeffs)

## BÀI TẬP CHƯƠNG 4 


In [ ]:
#Cau1

import numpy as np

def cofactor_matrix(A):
    n = A.shape[0]
    cofactor = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
            cofactor[i][j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    return cofactor

def adjoint_matrix(A):
    return cofactor_matrix(A).T

A = np.array([[1, 2, 3], [0, 4, 5], [1, 0, 6]])

cofactor = cofactor_matrix(A)
adjoint = adjoint_matrix(A)

print(cofactor)
print(adjoint)

[[ 24.   5.  -4.]
 [-12.   3.   2.]
 [ -2.  -5.   4.]]
[[ 24. -12.  -2.]
 [  5.   3.  -5.]
 [ -4.   2.   4.]]


In [30]:
#Cau2

from sympy import *

x, y, x1, y1, x2, y2, x3, y3 = symbols('x y x1 y1 x2 y2 x3 y3')

M = Matrix([[x**2 + y**2, x, y, 1],
            [x1**2 + y1**2, x1, y1, 1],
            [x2**2 + y2**2, x2, y2, 1],
            [x3**2 + y3**2, x3, y3, 1]])

coeffs = M.rref()[0]

print(coeffs)

Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
