## CHƯƠNG 6: CÁC KHÁI NIỆM: KHÔNG GIAN VECTOR, TÍCH TRONG VÀ TRỊ RIÊNG, VECTOR RIÊNG

### 1.2 Tích vô hướng, trực giao và ứng dụng 


In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich = np.inner(a, b)
print("Tích vô hướng của a và b bằng np.inner:", tich)


c = np.array([0, -1, 2])
d = np.array([3, 4, 0])
tich_cd = np.inner(c, d)
print("Tích vô hướng của c và d:", tich_cd)

def manual_inner_product(v1, v2):
    if len(v1) != len(v2):
        raise ValueError("Các vector phải có cùng chiều dài")
    return sum(x * y for x, y in zip(v1, v2))

tich_manual = manual_inner_product(a, b)
print("Tích vô hướng thủ công của a và b:", tich_manual)

def are_orthogonal(v1, v2):
    return np.inner(v1, v2) == 0

e = np.array([1, 0, 0])
f = np.array([0, 1, 0])
print("e và f có trực giao không?", are_orthogonal(e, f))

def project_vector(u, v):
    return (np.inner(u, v) / np.inner(v, v)) * v

proj_a_on_b = project_vector(a, b)
print("Hình chiếu của a lên b:", proj_a_on_b)

Tích vô hướng của a và b bằng np.inner: 32
Tích vô hướng của c và d: -4
Tích vô hướng thủ công của a và b: 32
e và f có trực giao không? True
Hình chiếu của a lên b: [1.66233766 2.07792208 2.49350649]


In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_result = np.dot(a, b)
print("Kết quả của np.dot(a, b):", dot_result)

inner_result = np.inner(a, b)
print("Kết quả của np.inner(a, b):", inner_result)

print("np.dot(a, b) và np.inner(a, b) có bằng nhau không?", np.allclose(dot_result, inner_result))

m = np.array([1, 2])  
n = np.array([3, 4])  
p = np.array([[1, 2, 3], [1, 1, 1]]) 
q = np.array([[4, 5, 6], [2, 2, 2]])  

dot_mn = np.dot(m, n)
print("Tích vô hướng của m và n bằng np.dot:", dot_mn)

inner_mn = np.inner(m, n)
print("Tích vô hướng của m và n bằng np.inner:", inner_mn)

inner_pq = np.inner(p, q)
print("Tích vô hướng của p và q (2x2) bằng np.inner:", inner_pq)

Kết quả của np.dot(a, b): 32
Kết quả của np.inner(a, b): 32
np.dot(a, b) và np.inner(a, b) có bằng nhau không? True
Tích vô hướng của m và n bằng np.dot: 11
Tích vô hướng của m và n bằng np.inner: 11
Tích vô hướng của p và q (2x2) bằng np.inner: [[32 12]
 [15  6]]


In [6]:
# Độ dài/chuẩn của vector: 

import numpy as np

a = np.array([1, 2, -3])

norm_a = np.linalg.norm(a)
print("Chuẩn của vector a bằng np.linalg.norm:", norm_a)

manual_norm = np.sqrt(np.dot(a, a))
print("Chuẩn của vector a tính thủ công:", manual_norm)

print("Kết quả từ np.linalg.norm và tính thủ công có bằng nhau không?", np.allclose(norm_a, manual_norm))

Chuẩn của vector a bằng np.linalg.norm: 3.7416573867739413
Chuẩn của vector a tính thủ công: 3.7416573867739413
Kết quả từ np.linalg.norm và tính thủ công có bằng nhau không? True


In [7]:
import numpy as np

a = np.array([1, 2, -3])

norm_l1 = np.linalg.norm(a, 1)
print("Chuẩn L1 của vector a bằng np.linalg.norm:", norm_l1)

manual_l1 = np.sum(np.abs(a))
print("Chuẩn L1 của vector a tính thủ công:", manual_l1)

print("Kết quả từ np.linalg.norm và tính thủ công có bằng nhau không?", np.allclose(norm_l1, manual_l1))

Chuẩn L1 của vector a bằng np.linalg.norm: 6.0
Chuẩn L1 của vector a tính thủ công: 6
Kết quả từ np.linalg.norm và tính thủ công có bằng nhau không? True


In [8]:
import math
import numpy as np

a = np.array([1, 2, -3])

def chuann(v, k):
    tong = 0
    for i in range(len(v)):
        tong = tong + abs(v[i])**k  
    ketqua = math.pow(tong, 1.0/k)  
    return ketqua

k = 2
result = chuann(a, k)
print("Chuẩn Lk của vector a với k =", k, "là:", result)

norm_l2 = np.linalg.norm(a, 2)
print("Chuẩn L2 bằng np.linalg.norm:", norm_l2)
print("Kết quả từ hàm tự định nghĩa và np.linalg.norm có bằng nhau không?", np.allclose(result, norm_l2))

Chuẩn Lk của vector a với k = 2 là: 3.7416573867739413
Chuẩn L2 bằng np.linalg.norm: 3.7416573867739413
Kết quả từ hàm tự định nghĩa và np.linalg.norm có bằng nhau không? True


In [9]:
import numpy as np

a = np.array([1, 2, -3])

norm_l1 = np.linalg.norm(a, 1)
print("Chuẩn L1 của vector a:", norm_l1)

Chuẩn L1 của vector a: 6.0


In [10]:
import numpy as np

a = np.array([1, 2, -3])

chuann = np.linalg.norm(a, 2)
print(chuann)

3.7416573867739413


In [20]:
import numpy as np

a = np.array([1, 2, -3])

norm_l2 = np.linalg.norm(a, 2)
print(norm_l2)

chuann_l3 = np.linalg.norm(a, 3)
print(chuann_l3)

3.7416573867739413
3.3019272488946263


In [13]:
import numpy as np

a = np.array([1, 2, -3])

norm_l3 = np.linalg.norm(a, 3)
print(norm_l3)

3.3019272488946263


In [14]:
import numpy as np

a = np.array([1, 2, -3])

chuann = np.linalg.norm(a, 1000)
print(chuann)

inf


c:\Users\QUOC TRONG\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\linalg\linalg.py:2590: RuntimeWarning: overflow encountered in power
  absx **= ord


In [15]:
import numpy as np

a = np.array([1, 2, -3])

norm_1000 = np.linalg.norm(a, 1000)
print(norm_1000)

inf


In [16]:
from scipy import linalg

a = [1, 2, -3]

norm_a = linalg.norm(a)
print(norm_a)

3.7416573867739413


In [17]:
from scipy import linalg

a = [1, 2, -3]

norm_a = linalg.norm(a, 100)
print(norm_a)

3.0


In [18]:
from scipy import linalg

a = [1, 2, -3]

norm_a = linalg.norm(a, 1000)
print(norm_a)

inf


c:\Users\QUOC TRONG\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\linalg\linalg.py:2590: RuntimeWarning: overflow encountered in power
  absx **= ord


### 2. Đọc thêm: Tổ hợp tuyến tính, Tổ hợp tuyến tính (linear combination)

In [19]:
import numpy as np

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])
MT = M.transpose()

print(M)
print(MT)

[[ 5 -4  3]
 [ 4  3 -2]
 [-4 -3 -1]
 [-9  8  6]]
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [21]:
import numpy as np

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])
MT = M.transpose()

v = (1.0/m) * MT.dot(mi)
print(v)

[1.3 0.9 0. ]


### 3. Tri riêng, vector riêng của ma trận và ứng dụng 

### 3.1.Bài toán dẫn nhập 

In [23]:
import numpy as np

A = np.array([[0.998, 0.136], [0.002, 0.864]])
x0 = np.array([0.95, 0.05])

x100 = x0
for _ in range(100):
    x100 = A.dot(x100)

print(x100)

[0.98550723 0.01449277]


In [24]:
import numpy as np

# Khai báo vector v0
v0 = np.array([0.95, 0.05])

print(v0)

[0.95 0.05]


In [25]:
import numpy as np
from numpy import linalg

A = np.array([[0.998, 0.136], [0.002, 0.864]])
v0 = np.array([0.95, 0.05])

A_power_100 = linalg.matrix_power(A, 100)

y = A_power_100.dot(v0)
print(y)

[0.98550723 0.01449277]


In [26]:
import numpy as np

A = np.array([[0.998, 0.136], 
              [0.002, 0.864]])
v0 = np.array([0.95, 0.05])

A_power = np.linalg.matrix_power(A, 100)

v100 = A_power @ v0

print("Trạng thái sau 100 tuần:")
print(f"x100 (có việc): {v100[0]:.6f}")
print(f"y100 (thất nghiệp): {v100[1]:.6f}")

Trạng thái sau 100 tuần:
x100 (có việc): 0.985507
y100 (thất nghiệp): 0.014493


In [27]:
import numpy as np

A = np.array([[0.998, 0.136],
              [0.002, 0.864]])


coefficients = np.array([
    [-0.002, 0.136], 
    [1, 1]         
])

constants = np.array([0, 1])

v_equilibrium = np.linalg.solve(coefficients, constants)

print("Trạng thái cân bằng:")
print(f"x = {v_equilibrium[0]:.6f} (tỉ lệ có việc làm)")
print(f"y = {v_equilibrium[1]:.6f} (tỉ lệ thất nghiệp)")

Trạng thái cân bằng:
x = 0.985507 (tỉ lệ có việc làm)
y = 0.014493 (tỉ lệ thất nghiệp)


In [30]:
import sympy as sym

x, y = sym.symbols('x y')

xy = sym.Matrix([x, y])

A = sym.Matrix([
    [1, -68],  
    [1, 1]     
])

v = sym.Matrix([0, 1])

nghiem = sym.solve(A*xy - v, (x, y))

print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


### 3.2 Trị riêng và vector riêng của ma trận 


In [31]:
import sympy as sym

A = sym.Matrix([[1, 6],
                [5, 2]])
u = sym.Matrix([6, -5])
lambda_ = -4

print("Kiểm tra bằng SymPy:")
print(A*u == lambda_*u) 

Kiểm tra bằng SymPy:
True


In [32]:
import numpy as np

A = np.array([[1, 6],
              [5, 2]])  
u = np.array([6, -5])  
lambda_ = -4           

if np.allclose(A.dot(u), lambda_ * u):
    print("u LÀ vector riêng của A ứng với λ = -4")
    print("A*u =", A.dot(u))
    print("λ*u =", lambda_ * u)
else:
    print("u KHÔNG phải vector riêng ứng với λ = -4")

u LÀ vector riêng của A ứng với λ = -4
A*u = [-24  20]
λ*u = [-24  20]


In [33]:
import sympy as sym

A = sym.Matrix([[1, 6],
                [5, 2]])
u = sym.Matrix([6, -5])

print("Chứng minh bằng SymPy:")
print("A*u =", A*u)
print("-4u =", -4*u)
print("Kết luận:", A*u == -4*u)

Chứng minh bằng SymPy:
A*u = Matrix([[-24], [20]])
-4u = Matrix([[-24], [20]])
Kết luận: True


In [34]:
import sympy as sym

x, y, Lambda = sym.symbols('x y Lambda')

I = sym.eye(2)

A = sym.Matrix([[2, 3],
                [3, -6]])

phuongtrinh = sym.Eq((Lambda*I - A).det(), 0)

nghiem = sym.solve(phuongtrinh, Lambda)

print([sym.N(phantu, 4) for phantu in nghiem])

[-7.000, 3.000]


In [35]:
import sympy as sym

A = sym.Matrix([[2, 3],
                [3, -6]])

nghiem = A.eigenvals()

print(sym.pretty(nghiem))

{-7: 1, 3: 1}


In [36]:
import sympy as sym

A = sym.Matrix([[2, 3],
                [3, -6]])
z = 3

A_minus_zI = A - z * sym.eye(2)

vector_rieng = A_minus_zI.nullspace()

print("Các vector riêng ứng với z =", z, ":")
sym.pprint(vector_rieng)

Các vector riêng ứng với z = 3 :
⎡⎡3⎤⎤
⎢⎢ ⎥⎥
⎣⎣1⎦⎦


In [37]:
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3], [3, -6]])
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1.0/3, 3], [1, 1]])

P_inv = LA.inv(P)

print("Ma trận nghịch đảo P^(-1):")
print(P_inv)

print("\nKiểm tra A = P*D*P^(-1):")
print(np.allclose(A, P @ D @ P_inv))

print("\nKiểm tra AP = PD:")
print("AP =", A @ P)
print("PD =", P @ D)
print("AP có bằng PD không?", np.allclose(A @ P, P @ D))

Ma trận nghịch đảo P^(-1):
[[-0.3  0.9]
 [ 0.3  0.1]]

Kiểm tra A = P*D*P^(-1):
True

Kiểm tra AP = PD:
AP = [[ 2.33333333  9.        ]
 [-7.          3.        ]]
PD = [[ 2.33333333  9.        ]
 [-7.          3.        ]]
AP có bằng PD không? True


In [38]:
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3], [3, -6]])
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1/3, 3], [1, 1]])

P_inv = LA.inv(P)

D_power_1000 = np.linalg.matrix_power(D, 1000)

A_power_1000 = P @ D_power_1000 @ P_inv

print("Ma trận A^1000:")
print(A_power_1000)

Ma trận A^1000:
[[-6.25396533e+08 -3.52488701e+08]
 [-3.52488701e+08  3.14573335e+08]]


In [39]:
import numpy as np

D = np.array([[-7, 0],
              [0, 3]])

D_squared = D ** 2

print("Ma trận D^2:")
print(D_squared)

Ma trận D^2:
[[49  0]
 [ 0  9]]


## BÀI TẬP CHƯƠNG 6 

### Câu 2: Sinh viên hãy viết các chương trình tính toán theo các công thức:

In [40]:
import numpy as np

def distance_between_vectors(u, v):
    """Tính khoảng cách Euclid giữa 2 vector u và v"""
    return np.linalg.norm(u - v)

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print("Khoảng cách giữa u và v:", distance_between_vectors(u, v))

Khoảng cách giữa u và v: 5.196152422706632


In [41]:
import numpy as np

def angle_between_vectors(u, v):
    cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
    return np.arccos(np.clip(cos_theta, -1.0, 1.0))  # Clip để tránh sai số số học

u = np.array([1, 0])
v = np.array([0, 1])
theta = angle_between_vectors(u, v)
print("Góc giữa u và v (radian):", theta)
print("Góc giữa u và v (độ):", np.degrees(theta))

Góc giữa u và v (radian): 1.5707963267948966
Góc giữa u và v (độ): 90.0


In [42]:
import numpy as np

def vector_projection(u, v):
    return (np.dot(u, v) / np.dot(v, v)) * v

u = np.array([1, 2])
v = np.array([3, 0])
p = vector_projection(u, v)
print("Phép chiếu của u lên v:", p)

Phép chiếu của u lên v: [1. 0.]
