# CHƯƠNG 7: KHÔNG GIAN VECTOR VÀ ÁNH XẠ TUYẾN TÍNH (PHẦN 1)

### 1. Giới thiệu một số ứng dụng của tích vector (dot product) 

In [1]:
import numpy as np
signals = np.array([[1,2],[3,4],[10,0]])
sample = np.array([3,-1])
np.inner(signals, sample) 

array([ 1,  5, 30])

### 1.1.Ứng dụng 1 – Nguyên lý tìm nốt nhạc trong chuỗi âm thanh (Audio search)

In [2]:
import numpy as np
A = np.array([0,0,-1,2,3,-1,0,1,-1,-1])
search_vector = np.array([0,1,-1])
len(A), len(search_vector) # nghĩa là = (10, 3)

(10, 3)

In [10]:
B = np.array([1])
B = np.resize(B, (len(A)-len(search_vector)+1, len(search_vector)))
B = np.asmatrix(B)
for i in range(len(A)-len(search_vector)+1): # so dong
    for j in range(len(search_vector)):
        B[i,j] = A[i+j]

print(B)

[[ 0  0 -1]
 [ 0 -1  2]
 [-1  2  3]
 [ 2  3 -1]
 [ 3 -1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1 -1 -1]]


In [12]:
C = np.inner(B, search_vector)
for i in range(len(A)-len(search_vector)+1): # tìm vị trí của vector vừa tìm thấy
    if ( C[0,i] == np.inner(search_vector, search_vector) ):
        print(i,B[i])

6 [[ 0  1 -1]]


### 1.2.Ứng dụng 2 – Tạo ảnh mẫu và làm mờ ảnh 

In [1]:
from PIL import Image, ImageDraw

# Mở hình ảnh đầu vào
input_image = Image.open("C:/Users/QUOC TRONG/Desktop/Đại số tuyến tính và ứng dụng/Lab7/hinhanh.jpg")
input_pixels = input_image.load()

# Bộ lọc làm mờ (blur kernel)
box_kernel = [
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
]

kernel = box_kernel
offset = len(kernel) // 2

# Tạo ảnh đầu ra
output_image = Image.new("RGB", input_image.size)
draw = ImageDraw.Draw(output_image)

# Áp dụng bộ lọc làm mờ
for x in range(offset, input_image.width - offset):
    for y in range(offset, input_image.height - offset):
        acc = [0, 0, 0]
        for a in range(len(kernel)):
            for b in range(len(kernel)):
                xn = x + a - offset
                yn = y + b - offset
                pixel = input_pixels[xn, yn]
                acc[0] += pixel[0] * kernel[a][b]
                acc[1] += pixel[1] * kernel[a][b]
                acc[2] += pixel[2] * kernel[a][b]
        draw.point((x, y), (int(acc[0]), int(acc[1]), int(acc[2])))

# Lưu ảnh sau khi làm mờ
output_path = "C:/Users/QUOC TRONG/Desktop/Đại số tuyến tính và ứng dụng/Lab7/hinhanhlammo.jpg"
output_image.save(output_path)

output_path


'C:/Users/QUOC TRONG/Desktop/Đại số tuyến tính và ứng dụng/Lab7/hinhanhlammo.jpg'

### 2. Ứng dụng: Xếp hạng các trang web với trị riêng và vector riêng

##### 2.1.Đơn giản hóa thuật toán Pagerank 

In [24]:
import numpy as np
A = np.array([[0,0,1.0/2, 1.0/2],
 [1.0/3,0,0,0],
 [1.0/3,0,0,1.0/2],
 [1.0/3,1.0,1.0/2,0]])
x = np.array([1,1,1,1]) 

In [25]:
x = np.dot(A, x)
print (x)

[1.         0.33333333 0.83333333 1.83333333]


In [26]:
# Hoặc 
x = np.array([1.0, 1.0, 1.0, 1.0])
for i in range(10):
    x = np.dot(A, x)
    print (i+1, x) 

1 [1.         0.33333333 0.83333333 1.83333333]
2 [1.33333333 0.33333333 1.25       1.08333333]
3 [1.16666667 0.44444444 0.98611111 1.40277778]
4 [1.19444444 0.38888889 1.09027778 1.32638889]
5 [1.20833333 0.39814815 1.06134259 1.33217593]
6 [1.19675926 0.40277778 1.06886574 1.33159722]
7 [1.20023148 0.39891975 1.06471836 1.3361304 ]
8 [1.20042438 0.40007716 1.06814236 1.3313561 ]
9 [1.19974923 0.40014146 1.06581951 1.3342898 ]
10 [1.20005466 0.39991641 1.06706131 1.33296762]


##### 2.2. [Đọc thêm] Xử lý dangling node trong thuật toán Pagerank

In [27]:
A = np.array([[0,0,1.0/2, 0.0],
 [1.0/3,0,0,0],
 [1.0/3,0,0,0.0],
 [1.0/3,1.0,1.0/2,0]])
for i in range(5):
    x = np.dot(A, x)
    print (i+1, x) 

1 [0.53353066 0.40001822 0.40001822 1.33346528]
2 [0.20000911 0.17784355 0.17784355 0.77787088]
3 [0.08892178 0.0666697  0.0666697  0.33343503]
4 [0.03333485 0.02964059 0.02964059 0.12964515]
5 [0.0148203  0.01111162 0.01111162 0.05557251]


In [30]:
x = np.array([1.0, 1.0, 1.0, 1.0])
A = np.array([[0,0,1.0/2, 1/4.0],
    [1.0/3,0,0,1/4.0],
    [1.0/3,0,0,1/4.0],
    [1.0/3,1.0,1.0/2,1/4.0]])
for i in range(7):
    x = np.dot(A, x)
    print (i+1, x) 

1 [0.75       0.58333333 0.58333333 2.08333333]
2 [0.8125     0.77083333 0.77083333 1.64583333]
3 [0.796875   0.68229167 0.68229167 1.83854167]
4 [0.80078125 0.72526042 0.72526042 1.74869792]
5 [0.79980469 0.70410156 0.70410156 1.79199219]
6 [0.80004883 0.71459961 0.71459961 1.77075195]
7 [0.79998779 0.70937093 0.70937093 1.78127035]


In [32]:
np.max(x) #  kết quả node D là node có giá trị lớn nhất


1.7812703450520826

##### 2.3. [Đọc thêm] Xử lý nhánh web reducible

In [33]:
A = np.array([[0.0, 0.0, 1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [1.0/3, 0.0, 1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [1/3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [1.0/3,1/2.0,1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0 ,1/2.0, 0.0, 0.0, 0.0,1/2.0, 0.0,0.0],
 [0.0, 0.0, 0.0,0.0, 0.0, 0.0, 1.0,1/2.0],
 [0.0, 0.0, 0.0,1/2.0, 1.0, 0.0, 0.0, 1/2.0],
 [0.0, 0.0, 0.0,0.0, 0.0,1/2.0, 0.0, 0.0]])
N = 8
x = np.array([1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N])
for i in range(7):
    x = np.dot(A, x)
    print (i+1, x)

1 [0.0625     0.10416667 0.04166667 0.16666667 0.125      0.1875
 0.25       0.0625    ]
2 [0.02083333 0.04166667 0.02083333 0.09375    0.14583333 0.28125
 0.23958333 0.09375   ]
3 [0.01041667 0.01736111 0.00694444 0.03819444 0.16145833 0.28645833
 0.23958333 0.140625  ]
4 [0.00347222 0.00694444 0.00347222 0.015625   0.15190972 0.30989583
 0.25086806 0.14322917]
5 [0.00173611 0.00289352 0.00115741 0.00636574 0.15842014 0.32248264
 0.23133681 0.15494792]
6 [0.0005787  0.00115741 0.0005787  0.00260417 0.16268808 0.30881076
 0.23907697 0.16124132]
7 [2.89351852e-04 4.82253086e-04 1.92901235e-04 1.06095679e-03
 1.54984086e-01 3.19697627e-01 2.44610822e-01 1.54405382e-01]


In [38]:
# Sinh viên tính toán ma trận M bằng Python như đoạn mã dưới đây:
d = 0.85
N = 8
x = np.array([1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N])
A = np.array([
    [0,   0,   1,   0,   0,   0,   0,   1],
    [1,   0,   0,   0,   0,   0,   0,   0],
    [0,   1,   0,   1,   0,   0,   0,   0],
    [0,   0,   0,   0,   0,   0,   1,   0],
    [0,   0,   0,   1,   0,   0,   0,   0],
    [0,   0,   0,   0,   1,   0,   0,   0],
    [0,   0,   0,   0,   0,   1,   0,   0],
    [0,   0,   0,   0,   0,   1,   0,   0]
], dtype=float)
M = d*A + ((1-d)/N)* np.ones([N,N])
print(M)

[[0.01875 0.01875 0.86875 0.01875 0.01875 0.01875 0.01875 0.86875]
 [0.86875 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875]
 [0.01875 0.86875 0.01875 0.86875 0.01875 0.01875 0.01875 0.01875]
 [0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.86875 0.01875]
 [0.01875 0.01875 0.01875 0.86875 0.01875 0.01875 0.01875 0.01875]
 [0.01875 0.01875 0.01875 0.01875 0.86875 0.01875 0.01875 0.01875]
 [0.01875 0.01875 0.01875 0.01875 0.01875 0.86875 0.01875 0.01875]
 [0.01875 0.01875 0.01875 0.01875 0.01875 0.86875 0.01875 0.01875]]


In [37]:
for i in range(7):
    x = np.dot(A, x)
    print (i+1, x) 

1 [0.25  0.125 0.25  0.125 0.125 0.125 0.125 0.125]
2 [0.375 0.25  0.25  0.125 0.125 0.125 0.125 0.125]
3 [0.375 0.375 0.375 0.125 0.125 0.125 0.125 0.125]
4 [0.5   0.375 0.5   0.125 0.125 0.125 0.125 0.125]
5 [0.625 0.5   0.5   0.125 0.125 0.125 0.125 0.125]
6 [0.625 0.625 0.625 0.125 0.125 0.125 0.125 0.125]
7 [0.75  0.625 0.75  0.125 0.125 0.125 0.125 0.125]


# BÀI TẬP CHƯƠNG 7 

In [41]:
# Câu 1
import numpy as np

# Ma trận Gaussian kernel (bản gốc từ tài liệu)
gaussian_kernel = np.array([[1, 4, 6, 4, 1],
                           [4, 16, 24, 16, 4],
                           [6, 24, 36, 24, 6],
                           [4, 16, 24, 16, 4],
                           [1, 4, 6, 4, 1]])

# Chuẩn hóa ma trận để tổng bằng 1 (phân số 256)
gaussian_kernel = gaussian_kernel / 256.0

# In ma trận Gaussian kernel đã chuẩn hóa
print("Ma trận Gaussian kernel đã chuẩn hóa:")
print(gaussian_kernel)


Ma trận Gaussian kernel đã chuẩn hóa:
[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]]


In [2]:
# Câu 2
import numpy as np

# Ma trận "nhân" ban đầu a và b
a = np.array([[0, -1, 0],
              [-1, 4, -1],
              [0, -1, 0]])

b = np.array([[-1, -1, -1],
              [-1, 8, -1],
              [-1, -1, -1]])

# Thực hiện phép nhân ma trận
result = np.dot(a, b)

# In kết quả
print("Ma trận kết quả sau phép nhân:")
print(result)


Ma trận kết quả sau phép nhân:
[[ 1 -8  1]
 [-2 34 -2]
 [ 1 -8  1]]
