### Câu 1: Phép toán cơ bản trên vector và ma trận (15 điểm)

In [13]:
import numpy as np

# Khai báo vector A và B
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

# a) A + B và 3A - 2B
sum_AB = A + B
expr = 3 * A - 2 * B

print("a) A + B =", sum_AB)
print("   3A - 2B =", expr)

# b) Tích vô hướng và góc giữa hai vector
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = np.degrees(np.arccos(cos_theta))

print("\nb) A · B =", dot_product)
print("   Góc giữa A và B ≈", round(angle_deg, 3), "độ")

# c) Tính C^T C
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

C_T_C = C.T @ C
print("\nc) C^T * C =\n", C_T_C)


a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]

b) A · B = -8
   Góc giữa A và B ≈ 108.376 độ

c) C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


### Câu 2: Nhân ma trận, định thức và hạng ma trận (20 điểm)

In [7]:
import numpy as np

M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# a) Tính tích M × N
product = M @ N
print("a) M × N =")
print(product)

# b) Tính định thức của ma trận M
det_M = np.linalg.det(M)
print("\nb) Định thức của M =", round(det_M, 3))
if np.isclose(det_M, 0):
    print("→ Ma trận M không khả nghịch (det = 0)")

# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của ma trận N =", rank_N)


a) M × N =
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M = 0.0
→ Ma trận M không khả nghịch (det = 0)

c) Hạng của ma trận N = 2


### Câu 3: Nghịch đảo ma trận và giải hệ phương trình

In [12]:
import numpy as np

P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
], dtype=float)

b = np.array([4, 7, 9, 5], dtype=float)

# a) Tìm ma trận nghịch đảo của P (nếu khả nghịch)
detP = np.linalg.det(P)
print("a) det(P) =", detP)
if not np.isclose(detP, 0):
    P_inv = np.linalg.inv(P)
    print("   P^{-1} =\n", P_inv)
else:
    print("   P không khả nghịch (det = 0)")

# b) Giải hệ P x = b bằng nghịch đảo
if not np.isclose(detP, 0):
    x = P_inv.dot(b)
    print("\nb) Nghiệm (x, y, z, w) =", x)

# c) Kiểm tra nghiệm bằng cách nhân P với vector x
if not np.isclose(detP, 0):
    check = P.dot(x)
    print("\nc) P.dot(x) =", check)
    print("   So sánh với b =", b)


a) det(P) = 86.00000000000004
   P^{-1} =
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm (x, y, z, w) = [0.46511628 2.10465116 1.65116279 0.96511628]

c) P.dot(x) = [4. 7. 9. 5.]
   So sánh với b = [4. 7. 9. 5.]


### Câu 4: Giá trị riêng, vector riêng và chuẩn hóa (20 điểm)

In [21]:
import numpy as np

# Định nghĩa ma trận Q
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

# a) Tìm các giá trị riêng
eigenvalues = np.linalg.eig(Q)[0]
print("a) Các giá trị riêng của Q:")
for i, val in enumerate(eigenvalues, 1):
    print(f"λ{i} = {val:.4f}")

# b) Tìm các vector riêng
eigenvectors = np.linalg.eig(Q)[1]
print("\nb) Các vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng ứng với λ{i+1} = {eigenvalues[i]:.4f}:")
    print(eigenvectors[:, i])

# c) Chuẩn hóa các vector riêng (độ dài bằng 1)
normalized_vectors = eigenvectors.copy()
for i in range(len(eigenvalues)):
    norm = np.linalg.norm(eigenvectors[:, i])
    normalized_vectors[:, i] = eigenvectors[:, i] / norm

print("\nc) Các vector riêng đã chuẩn hóa:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng chuẩn hóa ứng với λ{i+1}:")
    print(normalized_vectors[:, i])
    # Kiểm tra độ dài vector chuẩn hóa
    print(f"Độ dài vector: {np.linalg.norm(normalized_vectors[:, i]):.6f}\n")

a) Các giá trị riêng của Q:
λ1 = 3.4534+0.0000j
λ2 = 2.7733+1.4677j
λ3 = 2.7733-1.4677j

b) Các vector riêng tương ứng:
Vector riêng ứng với λ1 = 3.4534+0.0000j:
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Vector riêng ứng với λ2 = 2.7733+1.4677j:
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Vector riêng ứng với λ3 = 2.7733-1.4677j:
[-0.26206044+0.31354813j -0.78166743-0.j         -0.21963176-0.41685708j]

c) Các vector riêng đã chuẩn hóa:
Vector riêng chuẩn hóa ứng với λ1:
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Độ dài vector: 1.000000

Vector riêng chuẩn hóa ứng với λ2:
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Độ dài vector: 1.000000

Vector riêng chuẩn hóa ứng với λ3:
[-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]
Độ dài vector: 1.000000



### Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích

In [22]:
import numpy as np

# Định nghĩa ma trận R và vector b
R = np.array([[1, -2, 3],
              [2, 0, 1],
              [-1, 1, 4]])
b = np.array([10, 8, 7])

# a) Giải hệ phương trình Rx = b bằng np.linalg.solve()
x = np.linalg.solve(R, b)
print("a) Giải hệ phương trình Rx = b:", x)

# b) Xác định xem ma trận R có khả nghịch không. Nếu có, tính ma trận nghịch đảo và dùng nó để giải lại hệ
if np.linalg.det(R) != 0:
    R_inverse = np.linalg.inv(R)
    x_inverse = R_inverse @ b
    print("b) Ma trận R khả nghịch. Ma trận nghịch đảo của R:")
    print(R_inverse)
    print("Giải lại hệ bằng ma trận nghịch đảo:", x_inverse)
else:
    print("b) Ma trận R không khả nghịch.")

# c) Tính chuẩn Frobenius của ma trận R
frobenius_norm = np.linalg.norm(R, 'fro')
print("c) Chuẩn Frobenius của ma trận R:", frobenius_norm)

a) Giải hệ phương trình Rx = b: [2.7826087  0.04347826 2.43478261]
b) Ma trận R khả nghịch. Ma trận nghịch đảo của R:
[[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Giải lại hệ bằng ma trận nghịch đảo: [2.7826087  0.04347826 2.43478261]
c) Chuẩn Frobenius của ma trận R: 6.082762530298219
